### ISSUE TITLE
Computers don't load when a chunk keeps loaded

### ISSUE THREAD

**Issue by rpiera** [wacossusca34/Consoles#15]
When I go away from the computer (+-100 blocks) and then return the computer doesn't load if the chunk wasn't unloaded. I have many chunks that keep loaded in my map, spawn, subway system... Any computer in these chunks never will load again. You can try to keep a chunk loaded with Chunk Keeper and test it.

**Comment by wacossusca34** [comment]
I hate this bug.

**Comment by SeqSEE** [comment]
Something I think is similar, but not sure until I can(if I can) recreate it, seems like this can happen if the player me is in an area (my house) and the chunks stay loaded for "too long". 

There was only this error related to the consoles directly in my logs:

[01:11:44] [Console Painting Thread/INFO]: Warning, took more than 20ms to send packet

There were no other noticeable gameplay issues, so I proceeded to give myself a 2nd computer and place it and it loaded a console, but failed to update when commands were issued. I logged out and in and both the computers loaded. Not sure if this is the same issue.

**Comment by wacossusca34** [comment]
@SeqSEE thank you, not sure if that issue is related though. If you do get that message frequently in your console however, it means you have too many consoles rendering in your server. See source file: https://github.com/wacossusca34/Consoles/blob/master/consoles-core/src/main/java/ca/jarcode/consoles/internal/MapPainter.java#L125

That is the console painter code, which schedules repaints from the main thread and for simply sending all the packets your server is taking more than 20ms.

> so I proceeded to give myself a 2nd computer and place it ~5 blocks away and it loaded a console, but failed to update when commands were issued.

*sighs* this is another (different) known bug. I have no idea how to reproduce it but some people seem to still have ran into 'dead' console displays (it's actually a client-sided bug that consoles uses a pretty extensive solution to work around). Let me know if you find a way to reliably reproduce it.

**Comment by wacossusca34** [comment]
I have tried reproducing this on a test server with no success. Plugins that conflict with chunk loading/unloading events may produce this issue, so I am closing the issue until such plugin(s) are identified.
