### ISSUE TITLE
Add support for editing the computers files via nano or another native text editor

### ISSUE THREAD

**Issue by ChristoCoder** [wacossusca34/Consoles#38]
Im making a server that will use consoles for some cool stuff, I need to be able to edit the computers files on the server command line, not this crazy minecraft command text editor

**Comment by soccermitchy** [comment]
Duplicate of #5?

**Comment by wacossusca34** [comment]
Since the change to the way filesystems work on computers, you can actually open up the nodes in a text editor and edit the text to whatever you want. Just make sure it's not already loaded in a buffer on a computer. You can find them in `..server/plugins/ConsolesComputers/computers/some-computer/files/`.

Alternatively you can always download files using the `wget` program or the `wget()` function.
