### ISSUE TITLE
Can someone explain what removeRestrictions() does?

### ISSUE THREAD

**Issue by ChristoCoder** [wacossusca34/Consoles#39]

**Comment by soccermitchy** [comment]
It allows a computer to access some undocumented functions to do things like access the network via sockets or running commands on the computer. It requires someone with a certain permission (don't remember it off the top of my head) to right click a dialog thing on screen for it to do anything, but normal players cannot use it.

**Comment by wacossusca34** [comment]
All the documented functions and userdata (ie. you can find information about it with `man`) are meant to be used by the common player in survival mode. It doesn't allow them to cheat in items, or exploit server resources.

There are some special libraries that allow for more advanced access to the server, such as running console commands, broadcasting messages, disable/enabling plugins, loading and unloading world, and performing various tasks on specific players. The `server` library (merely a table of functions in lua that is added when restrictions are removed) allows all of this, and you can see these functions here:

https://github.com/wacossusca34/Consoles/blob/master/consoles-computers/src/main/java/ca/jarcode/consoles/computer/interpreter/libraries/ServerLibrary.java

Additionally, because of how the LuaN and LuaJ layers work, Java objects are effectively _wrapped_ in lua, and arrays are passed as tables with indexes `1-n`, so you can actually get the Bukkit player object and start doing all sorts of fun things with it.
