### ISSUE TITLE
After restarting server image have error view

### ISSUE THREAD

**Issue by Mabus13** [wacossusca34/Consoles#49]
After restarting server image have error view, like some pieces of image above original image in wrong places. Like "wrong puzzle".... After remove image - normal part of image is deleted, but buged part not delete. And it can be deleted only by hands like 2 hits for each tile.

**Comment by wacossusca34** [comment]
If you're on a bungee server, you will need to install the bungee plugin and setup consoles to work with bungee (in the config file). This happens when you switch servers that are using the same map IDs for different images (consoles can't keep track of them and the client gets confused).

If you're not on bungee, please find a way to produce the issue.

**Comment by Mabus13** [comment]
I not use bungee. Just solo server. 
images.json
{"consoleData":[{"location":{"world":"world","x":263.0,"y":77.0,"z":-192.0,"yaw":0.0,"pitch":0.0},"face":"WEST","w":7,"h":4}],"urls":["https://pp.vk.me/c629404/v629404673/18be/wpeRIz_3O9s.jpg"]}

It happened already twice. Maybe i can found issue but i not think that. =(((

**Comment by Mabus13** [comment]
Maybe it problem because i have sometimes server crashes. =( Need check.

**Comment by wacossusca34** [comment]
Again, I need a way to cause these issues. I can't fix bugs that I don't know how to cause.

**Comment by Mabus13** [comment]
You may close this. I think cause only server crash it very hard reproduce, for now.
