### ISSUE TITLE
Laging movements all players and some mobs.

### ISSUE THREAD

**Issue by Mabus13** [wacossusca34/Consoles#50]
Today with a shriek in the heart and chest pain, i turned off the plug-in consoles. And I notice another bad feature. With the included plug-in All the players jumping accompanied by a jerk every half second(or second). Laging also mobs. It very pity see lags on server with 5 players...

**Comment by wacossusca34** [comment]
Using spigot timings if you're encountering lag issues, Consoles shouldn't be related though, since 90% of its workload is off the main thread.

**Comment by Mabus13** [comment]
Timings it just numbers. I see fact. No plugin - no lags. (jerk in jumps) =( Ask any other player just make few simple jumps with plugin on and with off. And you see that different by eyes.

**Comment by wacossusca34** [comment]
> Timings it just numbers. I see fact.

No, spigot timings show exactly what is going on in your server. If you are going to refuse to provide proper information so that I can pinpoint issues, **do not make issues**. Saying that the plugin is 'lagging' your server with no statistics, no dumps, no timings, and no stack frames where there is high load is pointless.

Come back with debug information, and stop pestering me without proper evidence that my plugin is causing issues on your server.

**Comment by Mabus13** [comment]
You can try reproduce before refuse? T_T
